# This template creates a Cloudwatch kinesis destination.  This is intended to be the cross-account "destination" for
# Cloudwatch logs.  The source should be a Cloudwatch log group that has a subscription filter that points to the
# Cloudwatch destination created in this template.

AWSTemplateFormatVersion: "2010-09-09"
Parameters:
  sourceAccount:
    Description:  Account Number of Cloudwatch Log Source (e.g., Britecore)
    Type: String
  env:
    Description:  Environment
    Type: String
Resources:
  DestinationStream:
    Type: 'AWS::Kinesis::Stream'
    Properties:
      Name: !Join ["", [!Ref env, -bc-cloudwatch-destination]]
      RetentionPeriodHours: 168
      ShardCount: 1
      Tags:
        -
          Key: env
          Value: !Ref env
  CloudwatchSubscriptionRole:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName:  !Join ["", [!Ref env, "-cloudwatch-subscription"]]
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Principal:
              Service:
                - "logs.us-east-1.amazonaws.com"
            Action:
              - "sts:AssumeRole"
  CloudwatchSubscriptionPolicies:
    Type: "AWS::IAM::Policy"
    Properties:
      PolicyName: !Join ["", [!Ref env, "-cloudwatch-subscription"]]
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Action: "kinesis:PutRecord"
            Resource: !GetAtt DestinationStream.Arn
          -
            Effect: "Allow"
            Action: "iam:PassRole"
            Resource: !GetAtt CloudwatchSubscriptionRole.Arn
      Roles:
        -
          Ref: CloudwatchSubscriptionRole
  CloudwatchDestinationRevisions:
    Type: "AWS::Logs::Destination"
    Properties:
      DestinationName: !Join ["", [!Ref env, "-cloudwatch-britecore-revisions"]]
      RoleArn: !GetAtt CloudwatchSubscriptionRole.Arn
      TargetArn: !GetAtt DestinationStream.Arn
      DestinationPolicy: !Sub
          - '{"Version" : "2012-10-17","Statement" : [{"Effect" : "Allow", "Principal" : {"AWS" : "${sourceAccount}"},"Action" : "logs:PutSubscriptionFilter", "Resource" : "${destArn}"}]}'
          - { sourceAccount: !Ref sourceAccount, destArn: !GetAtt DestinationStream.Arn}

Outputs:
  CloudwatchDestionationArn:
    Value: !GetAtt DestinationStream.Arn
    Description:  The Kinesis Stream Arn
    Export:
      Name:  !Join ["", [!Ref env, PhysicalKinesisDestination]]
  CloudwatchDestinationRevisions:
    Value: !GetAtt CloudwatchDestinationRevisions.Arn
    Description:  The Cloudwatch Destination Arn for revisions.log
    Export:
      Name:  !Join ["", [!Ref env, CloudwatchDestinationRevisions]]

